# Ansilbe playbook to install Freeswitch on Debian 10 and 11 
# Update signalwire_freeswitch_key with your token from SignalWire 
- name: Install Freeswitch 
  vars:
    signalwire_freeswitch_key: pat_aW3Nn6RBYfijPLeN8GjRLC2E
    freeswitch_version: 'v1.10.7'
  hosts: localhost
  connection: local 
  remote_user: root
  tasks:
    - name: Install cmake apt
      ansible.builtin.apt:
        name: cmake
        state: present
    - name: Fetch FreeSWITCH GPG key
      get_url:
        url: https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg
        username: signalwire
        password: '{{ signalwire_freeswitch_key }}'
        dest: /usr/share/keyrings/signalwire-freeswitch-repo.gpg
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Auth Directory Creation 
      ansible.builtin.file:
        path: /etc/apt/auth.conf.d
        state: directory
        mode: '0755'
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Createing apt auth.conf.d 
      ansible.builtin.copy:
        dest: /etc/apt/auth.conf.d/freeswitch.conf
        owner: root
        group: root
        mode: '0700'
        content: 'machine freeswitch.signalwire.com login signalwire password {{ signalwire_freeswitch_key }}'
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Adding SignalWire FreeSWITCH binary and source repos
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg] https://freeswitch.signalwire.com/repo/deb/debian-release/ bullseye main
        state: present
        filename: freeswitch
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Adding SignalWire FreeSWITCH binary and source repos
      ansible.builtin.apt_repository:
        repo: deb-src [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg] https://freeswitch.signalwire.com/repo/deb/debian-release/ bullseye main
        state: present
        filename: freeswitch
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Updating apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Installing build dependencies for FreeSWITCH
      apt:
        pkg: freeswitch
        state: build-dep
        force: yes

    - name: Cloning libks repository
      git:
        repo: 'https://github.com/signalwire/libks.git'
        version: 'master'
        dest: /usr/local/src/libks

    - name: Building and installing libks
      shell: |
        cd /usr/local/src/libks
        cmake . -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/freeswitch/
        make
        make install
        ldconfig

    - name: Cloning libsignalwire repository
      git:
        repo: 'https://github.com/signalwire/signalwire-c.git'
        version: 'master'
        dest: /usr/local/src/signalwire-c

    - name: Building and installing libsignalwire
      shell: |
        cd /usr/local/src/signalwire-c
        cmake . -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/freeswitch/
        make
        make install
        ldconfig

    - name: Cloning spandsp repository
      git:
        repo: 'https://github.com/freeswitch/spandsp.git'
        version: 'master'
        dest: /usr/local/src/spandsp

    - name: Building and installing spandsp
      shell: |
        cd /usr/local/src/spandsp
        ./bootstrap.sh
        ./configure --prefix=/usr/local/freeswitch/
        make
        make install
        ldconfig

    - name: Cloning sofia-sip repository
      git:
        repo: 'https://github.com/freeswitch/sofia-sip.git'
        version: 'master'
        dest: /usr/local/src/sofia-sip

    - name: Building and installing sofia-sip
      shell: |
        cd /usr/local/src/sofia-sip
        ./bootstrap.sh
        ./configure
        make
        make install
        ldconfig

    - name: Cloning FreeSWITCH {{ freeswitch_version }}
      git:
        repo: 'https://github.com/signalwire/freeswitch.git'
        version: '{{ freeswitch_version }}'
        dest: /usr/local/src/freeswitch

    - name: Building FreeSWITCH
      shell: |
        cd /usr/local/src/freeswitch
        ./bootstrap.sh -j
        ./configure -C --prefix=/usr/local/freeswitch/
        make
        make install
        make all cd-sounds-install cd-moh-install

    - name: Configuring FreeSWITCH
      shell: |
        cp -R /usr/local/src/freeswitch/conf /usr/local/freeswitch
        ln -sf /usr/local/freeswitch/bin/fs_cli /usr/bin/fs_cli
        ln -sf /usr/local/freeswitch/bin/freeswitch /usr/bin/freeswitch

    - name: Creating systemd service file for FreeSWITCH
      copy:
        dest: /etc/systemd/system/freeswitch.service
        content: |
          [Unit]
          Description=FreeSWITCH
          After=syslog.target network.target local-fs.target

          [Service]
          Type=forking
          Environment=DAEMON_OPTS="-nonat"
          Environment=USER=freeswitch
          Environment=GROUP=freeswitch
          Environment=HOME=/usr/local/freeswitch
          WorkingDirectory=/usr/local/freeswitch
          User=freeswitch
          Group=freeswitch
          ExecStartPre=/bin/chown -R freeswitch:freeswitch /usr/local/freeswitch
          ExecStartPre=/bin/mkdir -p /usr/local/freeswitch/run
          ExecStartPre=/bin/chown -R freeswitch:freeswitch /usr/local/freeswitch/run
          ExecStart=/usr/local/freeswitch/bin/freeswitch -u freeswitch -g freeswitch -ncwait -nonat -nonatmap
          ExecReload=/bin/kill -HUP $MAINPID
          TimeoutSec=45s
          Restart=always
          RestartSec=90

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: freeswitch
        enabled: true
        state: started