# Ansilbe playbook to install Freeswitch on Debian 10 and 11 
# Update signalwire_freeswitch_key with your token from SignalWire 
- name: Install Freeswitch 
  vars:
    signalwire_freeswitch_key: pat_aW3Nn6RBYfijPLeN8GjRLC2E
  hosts: localhost
  connection: local 
  remote_user: root
  tasks:
    - name: Installing prerequisites
      ansible.builtin.apt:
        name:
          - autoconf
          - automake
          - bison
          - build-essential
          - curl
          - flex
          - g++
          - git
          - libjpeg-dev
          - libncurses5-dev
          - libtool
          - libtiff5-dev
          - libtiff-tools
          - libcurl4-openssl-dev
          - libgdbm-dev
          - libgmp-dev
          - libogg-dev
          - libsqlite3-dev
          - libssl-dev
          - libvorbis-dev
          - libpcre3
          - libpcre3-dev
          - libspeex-dev
          - libspeexdsp-dev
          - libedit-dev
          - libldns-dev
          - libopus-dev
          - libsndfile1-dev
          - libtool-bin
          - lua5.2
          - lua5.2-dev
          - pkg-config
          - zlib1g-dev
          - libavformat-dev
          - libavresample-dev
          - libswscale-dev
          - libyuv-dev
          - libvpx-dev
          - nasm
          - python3
          - python3-dev
          - python3-pip
          - wget
          - yasm
          - libavcodec-dev
          - libx264-dev
          - libasound2-dev
          - cmake
          - ca-certificates
          - libtool-bin
          - sqlite3
        update_cache: yes

    - name: Fetch FreeSWITCH GPG key
      get_url:
        url: https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg
        username: signalwire
        password: '{{ signalwire_freeswitch_key }}'
        dest: /usr/share/keyrings/signalwire-freeswitch-repo.gpg
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Auth Directory Creation 
      ansible.builtin.file:
        path: /etc/apt/auth.conf.d
        state: directory
        mode: '0755'
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: Createing apt auth.conf.d 
      ansible.builtin.copy:
        dest: /etc/apt/auth.conf.d/freeswitch.conf
        owner: root
        group: root
        mode: '0700'
        content: 'machine freeswitch.signalwire.com login signalwire password {{ signalwire_freeswitch_key }}'
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10

    - name: "Add SignalWire FreeSWITCH repo"
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg] https://freeswitch.signalwire.com/repo/deb/debian-release/ {{ ansible_distribution_release }} main
        state: present
        filename: freeswitch
      when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 10
      
    - name: Cloning FreeSWITCH v1.10.7
      git:
        repo: 'https://github.com/signalwire/freeswitch.git'
        version: 'v{{ freeswitch_version }}'
        dest: /usr/local/src/freeswitch

    - name: Building FreeSWITCH
      shell: |
        cd /usr/local/src/freeswitch
        ./bootstrap.sh -j
        ./configure -C
        make
        make install
        make all cd-sounds-install cd-moh-install

    - name: Configuring FreeSWITCH
      shell: |
        cp -R /usr/local/src/freeswitch/conf /usr/local/freeswitch
        ln -sf /usr/local/freeswitch/bin/fs_cli /usr/bin/fs_cli
        ln -sf /usr/local/freeswitch/bin/freeswitch /usr/bin/freeswitch

    - name: Creating systemd service file for FreeSWITCH
      copy:
        dest: /etc/systemd/system/freeswitch.service
        content: |
          [Unit]
          Description=FreeSWITCH
          After=syslog.target network.target local-fs.target

          [Service]
          Type=forking
          Environment=DAEMON_OPTS="-nonat"
          Environment=USER=freeswitch
          Environment=GROUP=freeswitch
          Environment=HOME=/usr/local/freeswitch
          WorkingDirectory=/usr/local/freeswitch
          User=freeswitch
          Group=freeswitch
          ExecStartPre=/bin/chown -R freeswitch:freeswitch /usr/local/freeswitch
          ExecStartPre=/bin/mkdir -p /usr/local/freeswitch/run
          ExecStartPre=/bin/chown -R freeswitch:freeswitch /usr/local/freeswitch/run
          ExecStart=/usr/local/freeswitch/bin/freeswitch -u freeswitch -g freeswitch -ncwait -nonat -nonatmap
          ExecReload=/bin/kill -HUP $MAINPID
          TimeoutSec=45s
          Restart=always
          RestartSec=90

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: freeswitch
        enabled: true
        state: started